package:
  name: vdbscan
  version: "0.9.2"

source:
  path: ./

requirements:
  build:
    - python
    - setuptools
    - gcc
    - libgcc
    - numpy
    - pkg-config
    - pkgconfig
  run:
    - libgcc
    - python
    - numpy

test:
  imports:
    - vdbscan

about:
  home: https://github.com/MITHaystack/VariantDBSCAN
  license: MIT
